openapi: '3.0.3'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
servers:
  - url: 'http://localhost:9090/api'
tags:
  - name: Quotes-end-point
    description: Gestion des quotes
  - name: Animals-end-point
    description: Gestion des animaux
  - name: Races-end-point
    description: Gestion des races
paths:
  /quotes:
    get:
      tags:
        - Quotes-end-point
      summary: Obtient une liste de toutes les quotes
      operationId: getQuotes
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        '404':
          description: Not Found
    post:
      tags:
        - Quotes-end-point
      summary: Ajoute une nouvelle quote
      operationId: addQuote
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Quote'
      responses:
        '201':
          description: quote crée
          headers:
            Location:
              description: URL de la quote crée
              schema:
                type: string
                format: uri
  /quotes/{id}:
    get:
      tags:
        - Quotes-end-point
      summary: Obtient une quote
      operationId: getQuote
      parameters:
        - name: id
          in: path
          description: numéro de la quote à obtenir
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Quote'
        '404':
          description: Not Found
      deprecated: false
    put:
        tags:
            - Quotes-end-point
        summary: Met à jour une quote
        operationId: updateQuote
        parameters:
            - name: id
              in: path
              description: numéro de la quote à mettre à jour
              required: true
              schema:
                type: integer
                format: int32
        responses:
            '204':
              description: OK
            '404':
              description: Not Found
  /animals:
    get:
      tags:
        - Animals-end-point
      summary: Obtient une liste de toutes les animaux
      operationId: getAnimals
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal'
        '404':
          description: Not Found
    post:
      tags:
        - Animals-end-point
      summary: Ajoute un nouvel animal
      operationId: addAnimal
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Animal'
      responses:
        '201':
          description: animal crée
          headers:
            Location:
              description: URL de l'animal crée
              schema:
                type: string
                format: uri
  /animals/{id}:
    get:
      tags:
        - Animals-end-point
      summary: Obtient un animal
      operationId: getAnimal
      parameters:
        - name: id
          in: path
          description: numéro de l'animal à obtenir
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Animal'
        '404':
          description: Not Found
      deprecated: false
  /races:
    get:
      tags:
        - Races-end-point
      summary: Obtient une liste de toutes les races
      operationId: getRaces
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Race'
        '404':
          description: Not Found
  /races/{id}:
    get:
      tags:
        - Races-end-point
      summary: Obtient une race
      operationId: getRace
      parameters:
        - name: id
          in: path
          description: numéro de la race à obtenir
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Race'
        '404':
          description: Not Found
      deprecated: false
components:
  schemas:
    Quote:
      description: toutes les caractéristiques d'une quote
      type: object
      properties:
        author:
          description: nom de l'auteur
          type: string
        citation:
          description: phrase de la citation
          type: string
        id:
          description: numéro auto-incrémenté de la citation
          type: integer
          format: int32
      title: Quote
    Animal:
      description: toutes les caractéristiques d'un animal
      type: object
      properties:
        name:
          description: nom de l'animal
          type: string
        noise:
          description: son que fait l'animal
          type: string
        species:
          description: espèce de l'animal
          type: string
        id:
          description: numéro auto-incrémenté de l'animal
          type: integer
          format: int32
      title: Animal
    Race:
      description: toutes les caractéristiques d'une race
      type: object
      properties:
        name:
          description: nom de la race
          type: string
        description:
          description: description de la race
          type: string
        id:
          description: numéro auto-incrémenté de la race
          type: integer
          format: int32